[book]
title = "ScafiWeb3"
authors = ["Tommaso Patriti"]
language = "it"
multilingual = true
src = "src"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[docs.html]
mathjax-support = true