name: Deploy application and releases on Pages
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      MDBOOK_VERSION: 0.4.21
      SCALA_TARGET: ./target/scala-3.5.2
      JS_COMPILED_TARGET: target/scala-3.5.2/scafiweb3-fastopt
    steps:
      - uses: actions/checkout@v3
      - name: Set sbt
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "sbt"
      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install --version ${MDBOOK_VERSION} mdbook
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Create artifact directory
        run: mkdir -p ./site
      - name: Build scala project
        run: |
          npm install
          sbt -J-Xmx6G fastLinkJS
          npm run build
      - name: Copy html page
        run: |
          cp -r ./dist ./site
          cp ./resources/linktree.html ./site/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  selenium-tests:
    runs-on: ubuntu-22.04
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: |
          npm install
          sbt -J-Xmx6G fastLinkJS
          sbt test
          sbt cucumber
      - name: Copy cucumber html page
        run: |
          cp ./target/test-report/cucumber/cucumber.html ./site/cucumber.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./site

  deploy-cucumber-results:
    environment:
      name: github-pages-cucumber
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: selenium-cucumber-tests
    steps:
      - name: Deploy Cucumber Reports to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

