name: Deploy application and releases on Pages
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      MDBOOK_VERSION: 0.4.43
      SCALA_TARGET: ./target/scala-3.5.2
      JS_COMPILED_TARGET: target/scala-3.5.2/scafiweb3-fastopt
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "sbt"
          

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Create artifact directory
        run: mkdir -p ./site

      - name: Build Scala project
        run: |
          npm install
          

      - name: Gen doc with vitepress
        run: |
          npm run docs:build
          cp -r ./docs/.vitepress/dist/* ./site



      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./site

      - name: Upload site artifact for deployment
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./site

      - name: Upload site artifact for testing
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
