name: Test
on:
  push:
    branches-ignore: [ 'doc' ]
  pull_request:
    branches: [ 'tests', 'dev' ]

  workflow_dispatch:

permissions:
  contents: read

jobs:

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Check scalafmt format
        run: sbt scalafmtCheckAll