name: Test
on:
  push:
    branches-ignore: [ 'doc', 'develop' ]
  pull_request:
    branches: [ 'tests', 'dev' ]

  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt test

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Check scalafmt format
        run: sbt scalafmtCheckAll